// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB2QZzALJ8-hh8b4TBLEOIwehh59sBkjMY',
    appId: '1:484196533426:web:d693748a8ca8d863b435ab',
    messagingSenderId: '484196533426',
    projectId: 'studentguide-fd173',
    authDomain: 'studentguide-fd173.firebaseapp.com',
    storageBucket: 'studentguide-fd173.appspot.com',
    measurementId: 'G-LHYFNT9V7D',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBsMUE8iFXuaZebDnIT0mSzMLeLPysV5F8',
    appId: '1:484196533426:android:2996c41d05233fd6b435ab',
    messagingSenderId: '484196533426',
    projectId: 'studentguide-fd173',
    storageBucket: 'studentguide-fd173.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDPkDViCO1eXcPGE5bstds3rZ62A9NXegs',
    appId: '1:484196533426:ios:fadded09d58f2caab435ab',
    messagingSenderId: '484196533426',
    projectId: 'studentguide-fd173',
    storageBucket: 'studentguide-fd173.appspot.com',
    iosBundleId: 'com.example.studentGuide',
  );
}
